-- Chạy file này trong Supabase Dashboard → SQL Editor → New query → Run
-- Project: odbxozdgskoyrohqojow

create extension if not exists "pgcrypto";

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null,
  address text not null,
  created_at timestamptz not null default now(),
  last_order_at timestamptz not null default now()
);

create index if not exists customers_phone_idx on public.customers (phone);
create index if not exists customers_last_order_at_idx on public.customers (last_order_at desc);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  number integer generated by default as identity,
  customer_id uuid references public.customers (id) on delete set null,
  name text not null,
  phone text not null,
  address text not null,
  amount bigint not null check (amount > 0),
  status text not null check (status in ('delivering', 'delivered', 'paid')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  delivered_at timestamptz,
  paid_at timestamptz
);

create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_customer_id_idx on public.orders (customer_id);

alter table public.customers enable row level security;
alter table public.orders enable row level security;

drop policy if exists "customers_anon_all" on public.customers;
create policy "customers_anon_all"
  on public.customers
  for all
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "orders_anon_all" on public.orders;
create policy "orders_anon_all"
  on public.orders
  for all
  to anon, authenticated
  using (true)
  with check (true);

grant select, insert, update, delete on public.customers to anon, authenticated;
grant select, insert, update, delete on public.orders to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
